[package]
name = "advent-of-code-2022"
version = "0.1.0"
authors = ["Michael Schertenleib <michael@michaelschertenleib.com>"]
edition = "2021"

[lib]
bench = false

[dependencies]
aoc-runner = "0.3.0"
aoc-runner-derive = "0.3.0"
itertools = "0.10.5"
